# Device for training (if not mentioned, then will be automatic)
# device: cuda

# Training params
training:
  learning_rate: 0.001
  num_epochs: 100
  batch_size: 32
  early_stopping_patience: 10
  num_adjacent_slices: 1  # [0, 1, 2]
  use_segmented_lungs: False

# Image Input dimensions
image:
  width: 512
  height: 512

# Thresholds
threshold:
  segmentation: 0.5
  classification: 0.75

